### ISSUE TITLE
Check-in scripts used to generate client

### ISSUE THREAD

**Issue by colemickens** [paralin/KubeNET#1]
Can you share the script that you invoke to do the auto-generation? (I realize you're doing manual, by-hand fixes afterward).

(I'm also curious if you tried this generator at all: https://github.com/Azure/autorest)

**Comment by paralin** [comment]
They are checked in.

https://github.com/paralin/KubeNET/tree/master/Resources/Scripts

**Comment by paralin** [comment]
Also that autorest project looks very promising and I think it'd be a good idea to transition this repository to using it soon.

**Comment by colemickens** [comment]
Thanks! Best of luck with Autorest -- I'd be curious to hear your experiences with it if you give it a shot.
